// <auto-generated />
using System;
using AFS_Visa_Application_REST_API.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFS_Visa_Application_REST_API.Migrations
{
    [DbContext(typeof(VisaApplicationContext))]
    [Migration("20231224230455_Add-Visa-Application")]
    partial class AddVisaApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AFS_Visa_Application_REST_API.Entity.Visa", b =>
                {
                    b.Property<Guid>("VisaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AppointmentRequired")
                        .HasColumnType("bit");

                    b.Property<string>("VisaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisaId");

                    b.ToTable("Visa");
                });

            modelBuilder.Entity("AFS_Visa_Application_REST_API.Entity.VisaApplication", b =>
                {
                    b.Property<Guid>("VisaApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentAssignedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DestinationCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VisaApplicationId");

                    b.HasIndex("VisaId");

                    b.ToTable("VisaApplication");
                });

            modelBuilder.Entity("AFS_Visa_Application_REST_API.Entity.VisaApplication", b =>
                {
                    b.HasOne("AFS_Visa_Application_REST_API.Entity.Visa", "Visa")
                        .WithMany("VisaApplications")
                        .HasForeignKey("VisaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visa");
                });

            modelBuilder.Entity("AFS_Visa_Application_REST_API.Entity.Visa", b =>
                {
                    b.Navigation("VisaApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
